grafana:
  enabled: false

server:
  retention: "7d"
  persistentVolume:
    enabled: true
    size: 8Gi
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  replicaCount: 1
  service:
    type: ClusterIP

alertmanager:
  enabled: true
  persistence:
    enabled: true
    size: 2Gi

prometheus-node-exporter:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

kube-state-metrics:
  enabled: true

prometheus-pushgateway:
  enabled: true
