apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracing-app
  namespace: default
  labels:
    app: tracing-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracing-app
  template:
    metadata:
      labels:
        app: tracing-app
    spec:
      containers:
        - name: app
          image: localhost/tracing-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: APP_PORT
              value: "8080"

            - name: DATABASE_URL
              value: "postgres://postgres:postgres@localhost:5432/app?sslmode=disable"

            - name: OTLP_ENDPOINT
              value: "tempo.monitoring.svc.cluster.local:4318"
            - name: OTEL_SERVICE_NAME
              value: "tracing-app"
            - name: OTEL_TRACES_SAMPLER
              value: "always_on"

        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "app"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: postgres-data
          emptyDir: {}
