apiVersion: v1
kind: Service
metadata:
  name: tracing-app
  namespace: default
  labels:
    app: tracing-app
spec:
  type: ClusterIP
  selector:
    app: tracing-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
