replicas: 1

tempo:
  multitenancyEnabled: false
  reportingEnabled: false
  retention: 24h

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi

  server:
    http_listen_port: 3200

  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces
      wal:
        path: /var/tempo/wal

  receivers:
    jaeger:
      protocols:
        grpc:
          endpoint: 0.0.0.0:14250
        thrift_binary:
          endpoint: 0.0.0.0:6832
        thrift_compact:
          endpoint: 0.0.0.0:6831
        thrift_http:
          endpoint: 0.0.0.0:14268
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
    opencensus: {}

service:
  type: ClusterIP
  port: 3200

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 5Gi
